### PR TITLE
Core: Add generics script loaders (I don't like use new).

### PR DESCRIPTION
**Pull request by SargeroDeV**
### Changes proposed

- Replace the use of new when registering a new script.

### Tests performed

- windowns 11

### How to Test the Changes:

1. Create a script and use instead of new the new macro.

### CODE REVIEW

**Comment by pangolp** [comment]
@Meltie2013 Any suggestions on this? Tests on Linux maybe?

**Comment by seobryn** [comment]
@pangolp I have to review that change, maybe works but i need to be sure

**Comment by Meltie2013** [comment]
I need more context on how this change works. Maybe a script showing on what is being done?
All I see is new Macros being used to replace another.

Documentation is a plus with this change.

**Comment by pangolp** [comment]
I believe TrinityCore has been using these macros for quite some time. But as far as I remember, it's a way to work it, but I don't really know if it's better or not. I also know that the previous system is fully compatible with this one, and that both can be used without problems. But yes, it requires that you receive it when you can. I am more familiar with the previous mechanism, but if it works, and does not hinder the use of the previous one, I have no problem in having both.

**Comment by SargeroDeV** [comment]
They are only macros, it is for those who already work as they do now in trinity, but anyone who wishes to do so can continue to use the new.

**Comment by pangolp** [comment]
As long as both systems can be used, it's fine with me, no problem.

**Review by pangolp — APPROVED** [review]
Considering that we are not modifying anything, but simply adding more content or a new way of defining/using things, I don't think there are any problems in merging this change.

**Pull request merged**
