### PR TITLE
Core: Implemented methods ListInRange: GetAttackableUnitListInRange, …

### PR DESCRIPTION
**Pull request by SargeroDeV**
…GetFriendlyUnitListInRange, GetAreatriggerListInRange, GetAreaTriggerListWithSpellIDInRange.

### Changes proposed

- Implement this methods

### Tests performed

- windowns 11

### How to Test the Changes:

1. using them in scripts.

### CODE REVIEW

**Comment by seobryn** [comment]
What is the Goal of this functions?

**Comment by kuramajssken001** [comment]
@SargeroDeV good job. It is very useful.

**Comment by SargeroDeV** [comment]
get such objects in lists, example:
```c++
std::list<Unit*> targets;
me->GetAttackableUnitListInRange(targets, 30.0f);
targets.resize(1);
```

**Comment by pangolp** [comment]
@Meltie2013 Any suggestions on this topic?

**Review by pangolp — APPROVED** [review]
Thanks.

**Pull request merged**
