### PR TITLE
Openssl and Update  Command Debug

### PR DESCRIPTION
**Pull request by HKevinH**
### Changes proposed

-  Cherry Pick https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/a7b244253a579f7c6826dbf732342efab648bc9d
-  Added Debug Lfg -> Cherry Picked  Source https://github.com/azerothcore/azerothcore-wotlk/commit/aa9a39e07f9263bcf39f0ce39ade9d945de351f9#diff-4d6939983b8b2bf1bdad835ce3dad389a3b1be64ef3897eb6d34b6f9eae5cb56

### How to Test the Changes:

1. Compile and run
---

- Thank you for collaborating with the project.
- For an efficient working methodology.
- It is obvious to make long pull request, unless it is necessary.
- A short pull request would be easy to test and approve.

### CODE REVIEW

**Comment by Meltie2013** [comment]
@HKevinH Lets keep the PR related to one thing and not multiple changes.

**Comment by HKevinH** [comment]
I'm sorry I missed it.

> @HKevinH Lets keep the PR related to one thing and not multiple changes.

**Comment by acidmanifesto** [comment]
The kalimafor changes is throwing me off here. Is that ment to be a seperate pr?

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thanks for the pr.

**Pull request merged**
