### PR TITLE
Fix (core): Flight Paths on Faction Changes

### PR DESCRIPTION
**Pull request by acidmanifesto**
### Changes proposed

- Level Appropiate Flight Points on Faction Change, currently all flight points open up for players for the factions they swap to regardless of level. We used the lfg system and create a LFG Zone to handle per level

### Issues addressed

- Closes source notes in characterhandler.cpp 
image

### Tests performed

1. Builds and runs

### How to Test the Changes:

1. Perform a .character changefaction on any mid or low level character just so you dont see all points as if it was max character.
2. observe flight points that are unlocked via flight mangers
3. Fine tuned the horde coordinates on faction swap as the old location was clippinged the player under the auction house.

horde level 21
image

alliance level 21
image

### Known issues and TODO list

- [ ] 
- [ ] 

---

- Thank you for collaborating with the project.
- For an efficient working methodology.
- It is obvious to make long pull request, unless it is necessary.
- A short pull request would be easy to test and approve.

### CODE REVIEW

**Review by seobryn — APPROVED** [review]
Looks preerty good for me

**Comment by acidmanifesto** [comment]
> Looks preerty good for me
> 

Lets avoid merging for the moment. I did a discussion with Meltie and we see a possible opportunity with this pr we want to explore.

**Comment by seobryn** [comment]
Hello, @acidmanifesto  @Meltie2013  do you think that PR needs more things to do or improve?

**Comment by Meltie2013** [comment]
@seobryn Don't think this PR was ready to be merged just yet. Please avoid merging PRs without conformation first.

**Pull request merged**
