### PR TITLE
feat (Update/Auth) Change of path in updates_include

### PR DESCRIPTION
**Pull request by SargeroDeV**
### Changes proposed

- Auth updates fixed

How to Test the Changes:
re-import the db auth and run the worldserver.exe

### CODE REVIEW

**Comment by pangolp** [comment]
That quest, we have it solved, but in a different way. However, we have to upload it in a different pull request, because if we were to revert the PR, for whatever reason, we would be modifying 2 absolutely different things.

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=4806 AND `SourceEntry`=17;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(23, 4806, 17, 0, 0, 9, 0, 0, 14400, 0, 0, 0, 0, '', 'Worgen Starter Zone- Quest 14400');

DELETE FROM `phase_area` WHERE `AreaId`=4806 AND `PhaseId`=181;
INSERT INTO `phase_area` (`AreaId`, `PhaseId`, `Comment`) VALUES (4806, 181, 'Worgen Starter Zone- Quest 14400');
```

I haven't tested the fix yet, because I started to do other things, but that was the change that someone suggested to me. In a while, I will try it and see if it works.

**Comment by seobryn** [comment]
@SargeroDeV another comment related to the PR body, please complete all the things related to pr description, for example Test performed, How to test your changes... and all related sections of the PR :), thanks!

**Comment by pangolp** [comment]
> another comment related to the PR body, please complete all the things related to pr description, for example Test performed, How to test your changes... and all related sections of the PR :), thanks!

Correct. We are not just making changes. We also want people who read it to be able to understand why we are making changes. That's why we use this template, and not another one. Please fill in the data. I agree with my colleague. Thank you.

**Comment by SargeroDeV** [comment]
ok

**Review by pangolp — APPROVED** [review]
Thanks.

**Pull request merged**
