### PR TITLE
DB: Fixed the update path.

### PR DESCRIPTION
**Pull request by SargeroDeV**
### Changes proposed

- It will now import the SQLs correctly.

### CODE REVIEW

**Comment by pangolp** [comment]
Isn't this actually done in master? Because I know @seobryn was working on it, but if not it's great. Welcome to it. I have to wait for him to confirm. Because he had been working on something similar.

**Comment by SargeroDeV** [comment]
yesterday when I was installing the source it was giving me problems because of the updates, I just put that way to get them, if they were working on it already, there is no problem with closing the PR then.

**Comment by pangolp** [comment]
> yesterday when I was installing the source it was giving me problems because of the updates, I just put that way to get them, if they were working on it already, there is no problem with closing the PR then.

No, I know they worked, but it seems to me that in the world. I didn't get that error, because I assemble the files by hand, I don't use the automatic updates, however, it's a fix that comes in handy. I just need @seobryn to check it. When he gives me the go ahead, we'll merge it.

**Review by pangolp — APPROVED** [review]
Thanks for the input, from my side, I think there is no problem, and that it can be merged.

**Review by pangolp — APPROVED** [review]
I don't know if in the authserver.conf, this is also disabled. I was the one who disabled them, but the idea was to enable them again.

**Comment by SargeroDeV** [comment]
the worldserver updates also the auth, that's why I never enable the auth ones.

**Pull request merged**
